/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "model_server_constants.h"

namespace fastserv {

const model_serverConstants g_model_server_constants;

model_serverConstants::model_serverConstants() {
}

} // namespace

