/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "model_server_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace fastserv {

} // namespace
