/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef model_server_CONSTANTS_H
#define model_server_CONSTANTS_H

#include "model_server_types.h"

namespace fastserv {

class model_serverConstants {
 public:
  model_serverConstants();

};

extern const model_serverConstants g_model_server_constants;

} // namespace

#endif
